version: "3"

services:
  telemetary:
    build: telemetary
    env_file:
      - ./telemetary/.env
    volumes:
      - ./telemetary:/app

  simulator:
    build:
      context: ./telemetary
      dockerfile: Dockerfile-simulator
    #stdin_open: true
    tty: true
    env_file:
      - ./telemetary/.env.simulator
    volumes:
      - ./telemetary:/app

  videostream:
    build: videostream
    env_file:
      - .videostream.env
    devices:
      - /dev/video0:/dev/video0
