version: "3"

services:
  telemetary:
    build: telemetary
    env_file:
      - .env
    volumes:
      - ./telemetary:/app

  videostream:
    build: videostream
    env_file:
      - .videostream.env
    devices:
      - /dev/video0:/dev/video0
